import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Quick Entroll",
  description: "Generated by Fazal",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gradient-to-br from-gray-300 via-gray-200 to-white `}
      >
        <Toaster
          toastOptions={{
            className: "",
            style: {
              border: "1px solid #713200",
              padding: "10px",
              color: "#713200",
            },
          }}
          position="top-right"
        />

        <div>
          <Link className="text-black" href={"/"}>
            <img
              width={100}
              height={100}
              style={{ borderRadius: "50%" }}
              src="/logo.png"
            />
          </Link>
        </div>

        {children}
      </body>
    </html>
  );
}
